RULE_WEIGHTS = {
    "DOMAIN_LINK_MISMATCH": 10,
    "DISPLAY_TARGET_MISMATCH": 35,
    "SUSPICIOUS_TLD": 20,
    "SHORTENER_LINK": 10,
    "SUSPICIOUS_ATTACHMENT": 25,
    "DOUBLE_EXTENSION": 35,
    "PHISHING_KEYWORDS": 8,
    "IP_LINK": 30,
    "URGENCY_LANGUAGE": 15,
    "ACCOUNT_THREAT_LANGUAGE": 18,
    "UNEXPECTED_ATTACHMENT_REQUEST": 20,
    "PAYMENT_REQUEST_LANGUAGE": 18,
    "BANK_CHANGE_LANGUAGE": 22,
    "INVOICE_PRESSURE_LANGUAGE": 16,
}

SUSPICIOUS_TLDS = {".ru", ".tk", ".xyz", ".top", ".click"}

SHORTENER_DOMAINS = {
    "bit.ly",
    "tinyurl.com",
    "t.co",
    "goo.gl",
}

SUSPICIOUS_ATTACHMENT_EXTENSIONS = {
    ".com",
    ".cpl",
    ".exe",
    ".hta",
    ".img",
    ".iso",
    ".jar",
    ".js",
    ".lnk",
    ".msi",
    ".pif",
    ".ps1",
    ".reg",
    ".scr",
    ".vbs",
    ".vb",
    ".wsf",
    ".wsh",
    ".cmd",
    ".bat",
    ".docm",
    ".xlsm",
}

PHISHING_KEYWORDS = {
    "urgent",
    "verify",
    "password",
    "account",
    "login",
    "suspended",
    "security",
    "confirm",
    "immediately",
    "dogrula",
    "doğrula",
    "sifre",
    "şifre",
    "hesap",
    "giris",
    "giriş",
    "askiya",
    "askıya",
    "guvenlik",
    "güvenlik",
    "hemen",
    "acil",
    "incele",
}

URGENCY_PHRASES = {
    "immediately",
    "within the next 24 hours",
    "urgent action required",
    "act now",
    "acil",
    "hemen",
    "derhal",
    "24 saat içinde",
    "en kisa surede",
    "en kısa sürede",
}

ACCOUNT_THREAT_PHRASES = {
    "account suspended",
    "account will be suspended",
    "temporarily locked",
    "suspicious login attempts",
    "confirm your identity",
    "protect your personal data",
    "hesabiniz askiya alinacak",
    "hesabınız askıya alınacak",
    "hesabiniz kilitlenecek",
    "hesabınız kilitlenecek",
    "supheli giris",
    "şüpheli giriş",
    "kimliginizi dogrulayin",
    "kimliğinizi doğrulayın",
    "kisisel verilerinizi koruyun",
    "kişisel verilerinizi koruyun",
}

ATTACHMENT_REQUEST_PHRASES = {
    "download and open the attached file",
    "open the attached file",
    "attached file",
    "attachment",
    "ekteki dosyayi acin",
    "ekteki dosyayı açın",
    "eki acin",
    "eki açın",
    "ekteki dosya",
    "ek dosya",
    "ekte paylasildi",
    "ekte paylaşıldı",
}

PAYMENT_REQUEST_PHRASES = {
    "payment",
    "make your payment",
    "complete the payment",
    "payment portal",
    "send the receipt",
    "invoice",
    "outstanding invoice",
    "amount due",
    "odeme",
    "ödeme",
    "odemeyi yapin",
    "ödemeyi yapın",
    "dekontu iletin",
    "dekontu gönderin",
    "fatura",
    "odenmemis",
    "ödenmemiş",
}

BANK_CHANGE_PHRASES = {
    "bank details have been updated",
    "updated bank details",
    "new iban",
    "new swift",
    "bank account update",
    "account details",
    "iban",
    "swift",
    "hesap bilgilerimizde guncelleme",
    "hesap bilgilerimizde güncelleme",
    "yeni iban",
    "yeni swift",
    "banka hesap bilgilerimiz degisti",
    "banka hesap bilgilerimiz değişti",
    "hesap detaylari",
    "hesap detayları",
}

INVOICE_PRESSURE_PHRASES = {
    "today",
    "within 24 hours",
    "late fee",
    "service interruption",
    "mandatory update",
    "zorunludur",
    "bugun icinde",
    "bugün içinde",
    "24 saat icinde",
    "24 saat içinde",
    "gecikme faizi",
    "hizmet kesintisi",
    "en kisa surede",
    "en kısa sürede",
}

TRUSTED_RELATED_DOMAINS = {
    "adobe.com",
    "adobesign.com",
    "adobelogin.com",
    "docusign.com",
    "docusign.net",
    "docs.google.com",
    "drive.google.com",
    "dropbox.com",
    "dropboxusercontent.com",
    "google.com",
    "googleapis.com",
    "googleusercontent.com",
    "microsoft.com",
    "office.com",
    "onedrive.live.com",
    "outlook.com",
    "powerbi.com",
    "sharepoint.com",
    "teams.microsoft.com",
    "zoom.us",
}

COMPANY_TRUSTED_DOMAINS = {
    "sasa.com.tr",
    "www.sasa.com.tr",
}

LOW_RISK_MAX = 24
MEDIUM_RISK_MAX = 54
